"""
Mock Government Opportunity Data Store (DEMO DATA)
===================================================
NOTICE: All records below are synthetic DEMO DATA created for the 2026 AI Builder
Hackathon. They are structured to mimic federal solicitations (SBIR/STTR, ARPA-H,
Grants.gov, and federal procurements) across five key hackathon startup categories
plus negative benchmark cases for evaluation.

When MongoDB is deployed by the team, the repository layer in repository.py
will query the real MongoDB collection instead of this file.
"""

from typing import List
from .models import Opportunity

MOCK_OPPORTUNITIES: List[Opportunity] = [
    # -------------------------------------------------------------------------
    # 1. AI & HEALTHCARE TECHNOLOGY CATEGORY
    # -------------------------------------------------------------------------
    Opportunity(
        id="opp-nsf-seed-fund-2026",
        program="NSF — America's Seed Fund (Phase I/II SBIR/STTR)",
        agency="National Science Foundation",
        agency_short="NSF",
        opportunity_type="sbir_grant",
        title="America's Seed Fund for Artificial Intelligence & DeepTech Digital Health",
        summary="Non-dilutive funding supporting early-stage technical startups conducting unproven high-risk R&D in AI algorithms, software automation, and biomedical applications with commercial potential.",
        funding_min=250000,
        funding_max=1500000,
        deadline="2026-09-30",
        days_left=47,
        is_active=True,
        target_industries=["healthcare", "software", "biotechnology", "digital health", "information technology"],
        target_technologies=["AI", "artificial intelligence", "machine learning", "NLP", "SaaS", "algorithms", "data science"],
        target_customers=["hospitals", "clinics", "physicians", "enterprise", "healthcare systems"],
        keywords=["ai", "healthcare", "nurse", "nursing", "hospital", "software", "deep tech", "r&d", "sbir", "digital health"],
        max_employees_limit=500,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=17,
        total_historical_funding="$8.4M",
        median_award="$420K",
        local_recipients_note="3 Utah recipients funded in past 2 years",
        is_demo_data=True,
    ),
    Opportunity(
        id="opp-nih-ninr-fasttrack-2026",
        program="NIH / HHS — Clinical Workflow & Nursing AI Commercialization (Fast-Track)",
        agency="National Institutes of Health",
        agency_short="NIH / HHS",
        opportunity_type="sbir_grant",
        title="Commercialization of AI in Clinical Workflows & Nursing Documentation Reduction",
        summary="Targeted non-dilutive Fast-Track grant combining Phase I feasibility and Phase II deployment for software platforms eliminating administrative charting friction for clinical staff.",
        funding_min=400000,
        funding_max=2200000,
        deadline="2026-10-15",
        days_left=62,
        is_active=True,
        target_industries=["healthcare", "clinical informatics", "nursing", "health systems", "software"],
        target_technologies=["AI", "SaaS", "clinical NLP", "EHR integration", "decision support"],
        target_customers=["hospitals", "nurses", "health systems", "inpatient care centers"],
        keywords=["nih", "hhs", "nursing", "clinical", "hospital", "burnout", "documentation", "ehr", "workflow", "fast-track"],
        max_employees_limit=500,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=24,
        total_historical_funding="$19.2M",
        median_award="$780K",
        local_recipients_note="5 Utah recipients funded under NINR/NLM",
        is_demo_data=True,
    ),
    Opportunity(
        id="opp-arpa-h-sprint-2026",
        program="ARPA-H — Health Systems Friction Reduction Sprint",
        agency="Advanced Research Projects Agency for Health",
        agency_short="ARPA-H",
        opportunity_type="ota_contract",
        title="Scalable Health Administration & Workforce Augmentation Sprint (BAA)",
        summary="Milestone-driven Other Transaction Authority (OTA) awards seeking high-velocity breakthrough technologies that achieve 10x administrative workload reductions for frontline clinicians.",
        funding_min=500000,
        funding_max=3000000,
        deadline="2026-09-18",
        days_left=35,
        is_active=True,
        target_industries=["healthcare", "health systems transformation", "workforce", "software"],
        target_technologies=["AI", "autonomous agents", "workflow automation", "SaaS"],
        target_customers=["hospitals", "health systems", "emergency departments"],
        keywords=["arpa-h", "workforce", "nursing", "administrative", "friction", "burnout", "hospital", "automation", "sprint"],
        max_employees_limit=None,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=9,
        total_historical_funding="$14.1M",
        median_award="$1.4M",
        local_recipients_note="1 Utah recipient funded under ARPA-H BAA sprint",
        is_demo_data=True,
    ),
    Opportunity(
        id="opp-va-vha-procure-2026",
        program="VA / VHA — Clinical Burden Reduction Pilot Procurement",
        agency="Veterans Health Administration",
        agency_short="VA / VHA",
        opportunity_type="procurement",
        title="Direct Commercial Pilot Procurement for VA Bedside Nursing Workflow AI",
        summary="Direct fixed-price commercial procurement contract to deploy and evaluate enterprise nursing software pilots inside Veterans Affairs Medical Centers across the nation.",
        funding_min=350000,
        funding_max=1200000,
        deadline="2026-11-12",
        days_left=90,
        is_active=True,
        target_industries=["healthcare", "veterans health", "federal procurement", "software"],
        target_technologies=["AI", "SaaS", "hospital operations", "clinical software"],
        target_customers=["hospitals", "va medical centers", "veterans health administration"],
        keywords=["va", "vha", "procurement", "hospital", "nursing", "pilot", "commercial", "enterprise"],
        max_employees_limit=None,
        requires_us_ownership=True,
        requires_active_rd=False,
        similar_companies_funded=12,
        total_historical_funding="$11.8M",
        median_award="$650K",
        local_recipients_note="2 Utah pilot contracts at Salt Lake City VA",
        is_demo_data=True,
    ),

    # -------------------------------------------------------------------------
    # 2. ADVANCED MANUFACTURING & AEROSPACE CATEGORY
    # -------------------------------------------------------------------------
    Opportunity(
        id="opp-dod-afwerx-sbir-2026",
        program="DoD / USAF — AFWERX Agility Prime Open Topic SBIR",
        agency="Department of the Air Force",
        agency_short="USAF / DoD",
        opportunity_type="sbir_grant",
        title="Dual-Use Autonomous Aerospace & Advanced Composite Manufacturing",
        summary="Phase I/II open topic non-dilutive defense SBIR awards for dual-use commercial technologies in autonomous flight controls, lightweight composite tooling, and precision aerospace manufacturing.",
        funding_min=150000,
        funding_max=1800000,
        deadline="2026-10-22",
        days_left=68,
        is_active=True,
        target_industries=["aerospace", "defense", "manufacturing", "advanced manufacturing", "robotics"],
        target_technologies=["autonomous systems", "robotics", "composites", "additive manufacturing", "drones", "avionics"],
        target_customers=["air force", "space force", "defense primes", "commercial aviation"],
        keywords=["afwerx", "aerospace", "aviation", "manufacturing", "defense", "flight", "drone", "composites", "sbir", "dual-use"],
        max_employees_limit=500,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=32,
        total_historical_funding="$28.5M",
        median_award="$1.2M",
        local_recipients_note="8 Utah aerospace/manufacturing companies funded",
        is_demo_data=True,
    ),
    Opportunity(
        id="opp-nasa-aeronautics-2026",
        program="NASA — Aeronautics Research Mission Directorate SBIR",
        agency="National Aeronautics and Space Administration",
        agency_short="NASA",
        opportunity_type="sbir_grant",
        title="High-Temperature Materials & Precision Automated Tooling for Aeronautics",
        summary="SBIR grants for breakthrough lightweight materials, thermal barrier coatings, and automated tooling systems accelerating next-generation commercial supersonic and hypersonic flight.",
        funding_min=150000,
        funding_max=1000000,
        deadline="2026-11-05",
        days_left=83,
        is_active=True,
        target_industries=["aerospace", "space", "advanced manufacturing", "materials science"],
        target_technologies=["composites", "high-temperature materials", "automation", "thermal management", "propulsion"],
        target_customers=["nasa", "commercial space", "aircraft manufacturers", "defense primes"],
        keywords=["nasa", "aerospace", "manufacturing", "propulsion", "materials", "hypersonic", "aircraft", "sbir"],
        max_employees_limit=500,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=14,
        total_historical_funding="$11.2M",
        median_award="$750K",
        local_recipients_note="4 Utah recipients in Hill AFB / space corridor",
        is_demo_data=True,
    ),

    # -------------------------------------------------------------------------
    # 3. CLIMATE & WATER INNOVATION CATEGORY
    # -------------------------------------------------------------------------
    Opportunity(
        id="opp-epa-doe-cleanwater-2026",
        program="EPA / DOE — Great Basin & Western Watershed Innovation Grant",
        agency="Environmental Protection Agency / Dept of Energy",
        agency_short="EPA / DOE",
        opportunity_type="grant",
        title="Advanced Desalination, Agricultural Water Reuse & Climate Resilience Systems",
        summary="Competitive grants funding software telemetry, membrane technologies, and energy-efficient water recycling hardware for municipal, agricultural, and industrial water conservation.",
        funding_min=300000,
        funding_max=2500000,
        deadline="2026-10-30",
        days_left=76,
        is_active=True,
        target_industries=["climate", "water", "cleantech", "agriculture", "environmental"],
        target_technologies=["IoT sensors", "water telemetry", "membrane filtration", "clean energy", "SaaS", "hardware"],
        target_customers=["municipalities", "utilities", "farms", "industrial water users", "irrigation districts"],
        keywords=["water", "climate", "conservation", "desalination", "agriculture", "clean tech", "iot", "drought", "epa", "doe"],
        max_employees_limit=None,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=19,
        total_historical_funding="$22.4M",
        median_award="$850K",
        local_recipients_note="6 Utah and Colorado watershed tech awardees",
        is_demo_data=True,
    ),
    Opportunity(
        id="opp-noaa-climate-resilience-2026",
        program="NOAA — Climate Resilience & Environmental Sensing SBIR",
        agency="National Oceanic and Atmospheric Administration",
        agency_short="NOAA",
        opportunity_type="sbir_grant",
        title="Predictive Climate Modeling, Micro-Weather Telemetry & Environmental Monitoring",
        summary="Small business funding for high-resolution environmental sensor arrays, hydrological forecasting software, and extreme weather mitigation platforms.",
        funding_min=175000,
        funding_max=650000,
        deadline="2026-11-18",
        days_left=95,
        is_active=True,
        target_industries=["climate", "environmental tech", "data analytics", "meteorology"],
        target_technologies=["AI", "remote sensing", "satellite analytics", "IoT", "modeling"],
        target_customers=["local governments", "insurance providers", "agriculture", "utilities"],
        keywords=["noaa", "climate", "weather", "sensors", "environmental", "satellite", "predictive", "sbir"],
        max_employees_limit=500,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=11,
        total_historical_funding="$6.8M",
        median_award="$400K",
        local_recipients_note="2 Mountain West weather analytics recipients",
        is_demo_data=True,
    ),

    # -------------------------------------------------------------------------
    # 4. CYBERSECURITY & CRITICAL INFRASTRUCTURE CATEGORY
    # -------------------------------------------------------------------------
    Opportunity(
        id="opp-dhs-cisa-cyber-2026",
        program="DHS / CISA — Critical Infrastructure Cybersecurity Innovation SBIR",
        agency="Cybersecurity and Infrastructure Security Agency / DHS",
        agency_short="CISA / DHS",
        opportunity_type="sbir_grant",
        title="Automated Zero-Trust Defense for Municipal Water, Energy & Healthcare Grids",
        summary="Funding commercial cybersecurity software to protect industrial control systems (ICS/SCADA), hospital networks, and municipal utilities from ransomware and state-sponsored cyber intrusions.",
        funding_min=200000,
        funding_max=1650000,
        deadline="2026-10-08",
        days_left=55,
        is_active=True,
        target_industries=["cybersecurity", "information security", "infrastructure", "software"],
        target_technologies=["zero trust", "AI security", "SCADA defense", "cryptography", "cloud security", "SaaS"],
        target_customers=["utilities", "hospitals", "financial institutions", "government agencies"],
        keywords=["cybersecurity", "cisa", "dhs", "zero-trust", "scada", "ransomware", "infrastructure", "threat intelligence", "sbir"],
        max_employees_limit=500,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=21,
        total_historical_funding="$18.9M",
        median_award="$720K",
        local_recipients_note="4 Utah Silicon Slopes cyber defense awardees",
        is_demo_data=True,
    ),
    Opportunity(
        id="opp-darpa-cyber-autonomy-2026",
        program="DARPA — Autonomous Cyber Reasoning & Vulnerability Repair (OTA)",
        agency="Defense Advanced Research Projects Agency",
        agency_short="DARPA",
        opportunity_type="ota_contract",
        title="Generative Agentic Cyber Reasoning & Automated Code Patching System",
        summary="High-impact contracts for autonomous AI systems capable of discovering zero-day vulnerabilities in critical software codebases and synthesizing provably secure real-time patches.",
        funding_min=750000,
        funding_max=4000000,
        deadline="2026-12-01",
        days_left=108,
        is_active=True,
        target_industries=["cybersecurity", "defense", "artificial intelligence", "software engineering"],
        target_technologies=["AI agents", "compiler security", "formal verification", "automated code repair"],
        target_customers=["dod", "intelligence community", "enterprise software vendors"],
        keywords=["darpa", "cyber", "vulnerability", "zero-day", "automated patching", "ai security", "ota"],
        max_employees_limit=None,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=8,
        total_historical_funding="$16.0M",
        median_award="$2.0M",
        local_recipients_note="1 Utah cybersecurity lab recipient",
        is_demo_data=True,
    ),

    # -------------------------------------------------------------------------
    # 5. WORKFORCE, EDUCATION & APPLIED TECHNOLOGY CATEGORY
    # -------------------------------------------------------------------------
    Opportunity(
        id="opp-nsf-exlent-workforce-2026",
        program="NSF — Experiential Learning for Emerging Technologies (ExLENT)",
        agency="National Science Foundation",
        agency_short="NSF",
        opportunity_type="grant",
        title="AI-Powered Technical Upskilling & Workforce Simulation Platforms",
        summary="Grants funding educational technology startups, interactive simulation environments, and AI-driven coaching tools preparing workers for careers in semiconductors, AI, and advanced manufacturing.",
        funding_min=200000,
        funding_max=1000000,
        deadline="2026-11-03",
        days_left=81,
        is_active=True,
        target_industries=["education", "workforce", "edtech", "software", "human resources"],
        target_technologies=["AI", "EdTech", "interactive simulation", "SaaS", "adaptive learning"],
        target_customers=["universities", "community colleges", "enterprise corporate training", "trade schools"],
        keywords=["nsf", "workforce", "education", "edtech", "training", "upskilling", "simulation", "coaching", "ai"],
        max_employees_limit=None,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=15,
        total_historical_funding="$9.5M",
        median_award="$500K",
        local_recipients_note="3 Utah EdTech recipients",
        is_demo_data=True,
    ),
    Opportunity(
        id="opp-onc-healthit-workforce-2026",
        program="HHS / ONC — Health IT Interoperability & Workforce Innovation Grant",
        agency="Office of the National Coordinator for Health IT",
        agency_short="HHS / ONC",
        opportunity_type="cooperative_agreement",
        title="FHIR API Interoperability & Clinical Workforce Data Integration",
        summary="Cooperative agreement funding software platforms demonstrating FHIR API interoperability and reducing data entry duplication for inpatient nursing and technical staff.",
        funding_min=150000,
        funding_max=500000,
        deadline="2026-10-28",
        days_left=75,
        is_active=True,
        target_industries=["healthcare", "health it standards", "interoperability", "workforce"],
        target_technologies=["FHIR APIs", "health informatics", "SaaS", "EHR standards"],
        target_customers=["hospitals", "health systems", "EHR vendors"],
        keywords=["onc", "fhir", "interoperability", "ehr", "health it", "workforce", "hhs"],
        max_employees_limit=None,
        requires_us_ownership=True,
        requires_active_rd=False,
        similar_companies_funded=14,
        total_historical_funding="$5.2M",
        median_award="$320K",
        local_recipients_note="2 Utah healthcare informatics recipients",
        is_demo_data=True,
    ),

    # -------------------------------------------------------------------------
    # 6. WEAK / ADJACENT / BENCHMARK OPPORTUNITIES (For testing discrimination)
    # -------------------------------------------------------------------------
    Opportunity(
        id="opp-doe-nuclear-exascale-2026",
        program="DOE — Nuclear Physics Exascale Simulation Consortium",
        agency="Department of Energy (Office of Science)",
        agency_short="DOE",
        opportunity_type="grant",
        title="High Performance Computing & Exascale Algorithms for Magnetic Fusion Containment",
        summary="Consortium grant targeting exascale computing algorithms for power grid modeling, nuclear simulation, and energy storage chemistry.",
        funding_min=1000000,
        funding_max=5000000,
        deadline="2026-12-15",
        days_left=123,
        is_active=True,
        target_industries=["nuclear physics", "energy", "supercomputing", "plasma physics"],
        target_technologies=["exascale HPC", "quantum chemistry", "tokamak modeling", "FORTRAN simulation"],
        target_customers=["national laboratories", "energy consortiums", "nuclear power facilities"],
        keywords=["energy", "nuclear", "fusion", "supercomputing", "doe", "physics", "plasma"],
        max_employees_limit=None,
        requires_us_ownership=True,
        requires_active_rd=True,
        similar_companies_funded=3,
        total_historical_funding="$12.0M",
        median_award="$3.5M",
        local_recipients_note="0 healthcare, cyber, or edtech recipients",
        is_demo_data=True,
    ),
    Opportunity(
        id="opp-usda-livestock-biogas-2026",
        program="USDA — Rural Dairy Livestock Methane Digestion Electrification",
        agency="United States Department of Agriculture",
        agency_short="USDA",
        opportunity_type="grant",
        title="Farm-Scale Anaerobic Bio-Digesters for Rural Dairy Cattle Operations",
        summary="Rural development grant supporting capital expenditure for farm manure anaerobic digestion equipment, methane capture gas scrubbers, and co-generation electric generators.",
        funding_min=50000,
        funding_max=500000,
        deadline="2026-12-30",
        days_left=138,
        is_active=True,
        target_industries=["agriculture", "farming", "dairy", "livestock", "rural energy"],
        target_technologies=["anaerobic digesters", "biogas scrubbers", "farm machinery", "co-generation"],
        target_customers=["dairy farms", "livestock producers", "rural cooperatives"],
        keywords=["usda", "farming", "dairy", "manure", "biogas", "methane", "agriculture", "livestock"],
        max_employees_limit=None,
        requires_us_ownership=True,
        requires_active_rd=False,
        similar_companies_funded=42,
        total_historical_funding="$15.0M",
        median_award="$220K",
        local_recipients_note="5 rural Utah agricultural dairy producers",
        is_demo_data=True,
    ),
]


def get_mock_opportunities() -> List[Opportunity]:
    """Returns the full in-memory list of synthetic demo opportunities."""
    return MOCK_OPPORTUNITIES
